# Generated by Django 4.1.7 on 2023-05-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
