# Generated by Django 4.1.7 on 2023-03-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
