# Generated by Django 4.1.7 on 2023-05-06 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_user_address_user_city_user_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='test',
        ),
    ]
