# Generated by Django 4.1.7 on 2023-05-06 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='task',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user_sp',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='task',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='passwordtoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paymentinformation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='task',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user_provider',
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='user',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='task',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.DeleteModel(
            name='PasswordToken',
        ),
        migrations.DeleteModel(
            name='PaymentInformation',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='UserSkill',
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
