# Generated by Django 4.1.7 on 2023-05-08 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_category_membership_skill_task_watchlist_userskill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinformation',
            name='credit_card',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='expiry_date',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='MembershipTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.IntegerField()),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_id', to='backend.paymentinformation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trans_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
