# Generated by Django 4.1.7 on 2023-05-08 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_paymentinformation_credit_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinformation',
            name='cvv',
            field=models.CharField(max_length=255),
        ),
    ]
