# Generated by Django 4.1.7 on 2023-05-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_paymentinformation_cvv'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptransaction',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
    ]
