# Generated by Django 4.1.7 on 2023-03-31 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_task_user_task_is_paid_task_user_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user_client',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user_provider',
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
