# Generated by Django 4.1.7 on 2023-03-31 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_remove_task_user_client_remove_task_user_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_provider', to=settings.AUTH_USER_MODEL),
        ),
    ]
