# Generated by Django 4.1.7 on 2023-05-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_membershiptransaction_trans_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='modify_date',
            field=models.DateTimeField(null=True),
        ),
    ]
