# Generated by Django 4.1.7 on 2023-05-09 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_notification_modify_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=6)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='category_price', to='backend.category')),
            ],
        ),
    ]
