# Generated by Django 4.1.7 on 2023-04-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='create_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='modify_date',
            field=models.DateTimeField(null=True),
        ),
    ]
