# Generated by Django 4.1.7 on 2023-05-13 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_task_booking_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
