# Generated by Django 4.1.7 on 2023-04-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_skill_alter_question_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='test_field',
            field=models.BooleanField(default=False),
        ),
    ]
