# Generated by Django 4.1.7 on 2023-04-04 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_skill_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='test_field',
        ),
    ]
