# Generated by Django 4.1.7 on 2023-04-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='create_date',
            field=models.DateTimeField(null=True),
        ),
    ]
