# Generated by Django 4.1.7 on 2023-05-14 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_remove_membershiptransaction_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12, null=True)),
                ('admin_fee', models.DecimalField(decimal_places=0, default=0, max_digits=12, null=True)),
                ('total_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, null=True)),
                ('is_payee', models.BooleanField(default=0, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_trans', to='backend.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_trans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_sp', models.TextField(blank=True, null=True)),
                ('comment_client', models.TextField(blank=True, null=True)),
                ('rating_sp', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True)),
                ('rating_client', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True)),
                ('create_date', models.DateTimeField(null=True)),
                ('modify_date', models.DateTimeField(null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_review', to='backend.task')),
                ('user_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rev_user_client', to=settings.AUTH_USER_MODEL)),
                ('user_sp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rev_user_sp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
