# Generated by Django 4.1.7 on 2023-05-21 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_transaction_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='provider_review',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='user_review',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
