# Generated by Django 4.1.7 on 2023-04-09 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_membership_skill_alter_question_create_date_and_more'),
        ('backend', '0017_alter_skill_skill_name'),
    ]

    operations = [
    ]
