# Generated by Django 4.1.7 on 2023-04-14 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_question_create_date_and_more'),
        ('backend', '0021_alter_userskill_user'),
    ]

    operations = [
    ]
