# Generated by Django 4.1.7 on 2023-04-24 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_offer_admin_fee_offer_total_price_alter_offer_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='membership',
        ),
    ]
