# Generated by Django 4.1.7 on 2023-04-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_alter_task_user_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
