# Generated by Django 4.1.7 on 2023-04-26 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_paymentinformation'),
        ('backend', '0035_alter_task_create_date_alter_task_modify_date'),
    ]

    operations = [
    ]
