# Generated by Django 4.1.7 on 2023-04-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_address_paymentinformation_passwordtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='long',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='location_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
