# Generated by Django 4.1.7 on 2023-04-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_merge_20230426_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinformation',
            name='credit_card',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='cvv',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='expiry_date',
            field=models.CharField(max_length=50),
        ),
    ]
