# Generated by Django 4.1.7 on 2023-04-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_task_lat_task_long_alter_task_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='location',
            field=models.TextField(),
        ),
    ]
