# Generated by Django 4.1.7 on 2023-04-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_alter_task_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='location',
            field=models.TextField(null=True),
        ),
    ]
