# Generated by Django 4.1.7 on 2023-04-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_alter_paymentinformation_credit_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinformation',
            name='credit_card',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='cvv',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='expiry_date',
            field=models.CharField(max_length=50),
        ),
    ]
