# Generated by Django 4.1.7 on 2023-05-05 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_user_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='user',
            name='long',
        ),
    ]
