# Generated by Django 4.1.7 on 2023-05-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0045_remove_user_lat_remove_user_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unit',
            field=models.CharField(blank=True, default='-', max_length=10, null=True),
        ),
    ]
