# Generated by Django 4.1.7 on 2023-05-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0046_alter_user_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskill',
            name='skill',
            field=models.CharField(max_length=50),
        ),
    ]
