# Generated by Django 4.1.7 on 2023-05-05 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0047_alter_userskill_skill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSkill',
        ),
    ]
