# Generated by Django 4.1.7 on 2023-05-05 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0050_user_email_verified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
