# Generated by Django 4.1.7 on 2023-05-05 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0051_delete_membership'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
